basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views
# TEMPLATE TAGGING

app_name = 'basic_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    # path('relative/', views.relative, name='relative'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('special/', views.special, name='special'),

]

learning_project/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout', views.user_logout, name='logout'),
    path('special', views.special, name='special'),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

from django.core import validators


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from basic_app.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return render(request, 'basic_app/special.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried to login and failed')
            print('Username: {} and password {}'.format(username, password))
            return HttpResponse('invalid login details suspplied')
    else:
        return render(request, 'basic_app/login.html', {})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <title>Base Page</title>
{#<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}

</head>

<body>

    <!-- Grey with black text -->
    <nav class="navbar navbar-expand-sm bg-dark .navbar-dark">
      <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'index' %}">HOME</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
                    </li>
                {% endif %}
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'basic_app:special' %}">Special</a>
                </li>
            </ul>
      </div>
    </nav>

    <div class="container">
           {% block body_block %}
             <!--Anythings out of this block it will be inherited if you extend  -->
           {% endblock %}
    </div>
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>

{#{% load my_extras %}#}

{% extends 'basic_app/base.html' %}
    {% block body_block %}
        <div class="jambotron">

        <h1 align="center">Welcome to Home Page</h1>

        <h2>Django level five!</h2>

        </div>
    {% endblock %}

templates/basic_app/login.html
<<!DOCTYPE html>

{% extends 'basic_app/base.html' %}
    {% load static %}

    {% block body_block %}
        <div class="jumbotron">
                <h1>Please Login</h1>
              <form action="{% url 'basic_app:user_login' %}" method="POST">
                    {% csrf_token %}
                  <label for="username">Username</label>
                  <input type="text" name="username" placeholder="Ener username">

                  <label for="password">Password</label>
                  <input type="text" name="password">

                  <input type="submit" name="" value="Login">
               </form>
        </div>
    {% endblock %}

templates/basic_app/registration.html
<!DOCTYPE html>

{% extends 'basic_app/base.html' %}
    {% load static %}

    {% block body_block %}
        <div class="jumbotron">

        {% if registered %}
            <h1>Thank you for registering!</h1>
            {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the form:</h3>

            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
        </div>
    {% endblock %}

templates/basic_app/special.html
<!DOCTYPE html>

{% extends 'basic_app/base.html' %}
    {% load static %}
    {% block body_block %}
        <div class="jambotron">

        <h1 align="center">Welcome to special Page</h1>

        <h2 align="center"><img src="{% static 'images/profile_pic/horse.webp' %}" alt=""></h2>

        </div>
    {% endblock %}